### ISSUE TITLE
Item.CloneTo() does not work in 7.2 Update-5 and 8.1 Initial

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#105]

**Comment by pveller** [comment]
I am looking at what changed in 8.1 and I suspect a defect in the new logic. It looks like Sitecore tried to support both old and new style of cloning but ... failed at it? I may be missing something. Here's the code that I am analyzing right now and not everything makes sense to me:

```csharp
    private ItemUri GetItemUriFromSourceItem()
    {
      ItemUri itemUri1 = (ItemUri) null;
      string itemUri2 = this.Fields[FieldIDs.Source].GetValue(false, false);
      string itemUri3 = this.Fields[FieldIDs.SourceItem].GetValue(false, false);
      if (!string.IsNullOrEmpty(itemUri2))
        itemUri1 = ItemUri.Parse(itemUri2);
      if (string.IsNullOrEmpty(itemUri3))
        return (ItemUri) null;
      Sitecore.Data.Version version = itemUri1 == (ItemUri) null ? this.Version : itemUri1.Version;
      return new ItemUri(new ItemUri(itemUri3).ToString(false), this.Language, version, this.Database);
    }
```

Shouldn't it use either `itemUri2` or `itemUri3`? The code determines version from the `__Source` field but always expects the link to be in the `__Source Item` field. I am sure it has to do with previous issues of dealing with versions in clones. It's probably not hard to fix in FakeDb by just cloning into both old and new field but it's probably worth posting these details to Sitecore Support. They could have easily supported old clones if the logic of this method used just the `__Source` in the absence of `__Source Item`.

p.s. surprisingly the new `FieldIDs.SourceItem` is not marked `readonly`. You can redefine by assigning a new ID to it. Dangerous :) I will sure add that to my bug report.

/cc @techphoria414

**Comment by pveller** [comment]
I posted 452835 ... and will try to fix FakeDb as well :)
