### ISSUE TITLE
Advice on Rainbow support

### ISSUE THREAD

**Issue by hermanussen** [sergeyshushlyapin/Sitecore.FakeDb#112]
Hi guys,

Since we've recently switched to Unicorn 3 on a project, I'd like to add support for the https://github.com/kamsar/Rainbow serialization format. I've got a pretty good idea on how to do this in Sitecore.FakeDb.Serialization, which would even allow people to mix normal serialization with Rainbow. But it might require a dependency on Rainbow (which is available through NuGet: https://www.nuget.org/packages/Rainbow).

Do you guys think I should create a separate project (and if so, what would the name be)? Or would it be ok to add the Rainbow dependency to Sitecore.FakeDb.Serialization? The latter would probably be easier to implement and more user friendly to configure, but the first is a little more pure.

Any thoughts?

Robin

**Comment by sergeyshushlyapin** [comment]
Hi Robin,
// cc: @kamsar

That is interesting. Rainbow uses FakeDb to write unit tests and FakeDb builds an integration with Rainbow :)

I think it's very important to keep the assemblies independent, so my vote is definitely for the new project Sitecore.FakeDb.Rainbow.

**Comment by pveller** [comment]
+ 1 for `Sitecore.FakeDb.Rainbow` and I definitely like the symmetry with:

>> Rainbow uses FakeDb to write unit tests and FakeDb builds an integration with Rainbow

:)

**Comment by hermanussen** [comment]
Thanks for the feedback. _Sitecore.FakeDb.Rainbow_ it is. Would it be ok if that project would have a dependency with _Sitecore.FakeDb.Serialization_?

I'm definitely going to have some abstractions that span both serialization projects. So those can then be in _Sitecore.FakeDb.Serialization_.

I hadn't thought about the symmetry there. Nice! I do hope the universe won't explode because of this ;-)

**Comment by hermanussen** [comment]
Maybe _Sitecore.FakeDb.Serialization.Rainbow_ would be a better name anyway?

**Comment by pveller** [comment]
I would leave naming up to you. Either one sounds good to me. I see how `Serialization` adds more *meaning* to it. And it's fine to have the main `Serialization` NuGet as a dependency. You anyway require main `Sitecore.FakeDb`, right?

**Comment by hermanussen** [comment]
Certainly. _DsDbItem_ and _DsDbTemplate_ inherit from their non-deserialized counterparts anyway. The only thing different from the normal serialization project will be the format that is used to deserialize from (.yml instead of .item files).

_Sitecore.FakeDb.Serialization.Rainbow_ it is. Thanks for the feedback guys!

**Comment by sergeyshushlyapin** [comment]
Hi guys,
If nobody object, I'll close it for now. Feel free to reopen if necessary.
