### ISSUE TITLE
Unable to create a `db` context if HttpContext is already set

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#114]
Trying to create a new `db` instance if the `HttpContext.Current` is already set fails with `ArgumentNullException`:

```csharp
[Fact]
public void ShouldNotFailIfHttpContextIsAlreadySet()
{
  // arrange
  var request = new HttpRequest(string.Empty, "http://mysite", string.Empty);
  var response = new HttpResponse(new StringWriter());

  HttpContext.Current = new HttpContext(request, response);
  try
  {
    // act
    using (new Db("master")) // <- Fails here
    {
    }
  }
  finally
  {
    HttpContext.Current = null;
  }
}
```

StackTrace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: folder
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.Configuration.Factory.LoadAutoIncludeFiles(ConfigPatcher patcher, String folder)
   at Sitecore.Configuration.Factory.LoadAutoIncludeFiles(XmlNode element)
   at Sitecore.Configuration.Factory.GetConfiguration()
   at Sitecore.Configuration.Factory.GetConfigNode(String xpath, Boolean assert)
   at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.Configuration.Factory.CreateObject(String configPath, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name)
   at Sitecore.Data.Database.GetDatabase(String databaseName)
   at Sitecore.FakeDb.Db..ctor(String databaseName) in 
```

It happens when Sitecore tries to load auto-include configs, but the `MainUtil.MapPath()` method is unable to resolve the proper path and returns *null*.

This test also makes *all* the other tests in the solution crazy and failing in random order.

**Comment by pveller** [comment]
Right. Our practice is to always set HttpContext.Current within using of Db and always set back to null in a finally before the end of the using. Basically contain it. You will also find that site context needs to be faked after you set HttpContext. All kinds of internal assumptions Sitecore makes (and takes different routes) based on weather HttpContext.Current == null or not.

You think we can do something about it in FakeDb? I long ago accepted this as a reality ;)

**Comment by sergeyshushlyapin** [comment]
Agree. It seems that is out of our control. Just thought it could be a sequel of #103.

**Comment by Manoharan13** [comment]
Hi there,
I’m new to Sitecore.FakeDb. I’m using latest version of FakeDb to write unit test cases for some extensions methods. When I execute those test cases from my local using Resharper/MS Test, it is working fine. But I’m getting the “System.ArgumentNullException : Value cannot be null. Parameter name: folder” error when I execute the test cases in SonarQube with OpenCover and NUnit. Below are the details. I’ve followed the installation steps from https://github.com/sshushliapin/Sitecore.FakeDb/wiki/Installation and I’m not sure if I’m missing some config files. Please help here.
public static class ItemExtensions
{
public static string MediaUrl(this Item item, ID mediaFieldId, MediaUrlOptions options = null)
        {
            var targetItem = item.TargetItem(mediaFieldId);
            return targetItem == null ? string.Empty : (MediaManager.GetMediaUrl(targetItem) ?? string.Empty);
        }
}
[Test]
        public void MediaUrlTest()
        {
            using (var db = new Db("web")
            {
                new DbItem("UtilityNav", new ID("{xxxxx}")) { { "Title", "NL Site" } }
            })
            {
                var item = db.GetItem("{xxxxx}");
                var res = item.MediaUrl(item.ID);
                Assert.IsNotNull(res);
            }
        }
OpenCover – Nunit Report
 
![NUnitErrror](https://user-images.githubusercontent.com/49951509/58717099-72744180-8398-11e9-93ca-0c1c9b3c43b3.png)

Thanks
