### ISSUE TITLE
Does Not Work With NUnit 3.0+

### ISSUE THREAD

**Issue by ncipollina** [sergeyshushlyapin/Sitecore.FakeDb#116]
I was attempting to run some unit tests with Sitecore.FakeDb and NUnit 3.0 and was unable to get it to work.  It looks like NUnit 3.0 might be running it's unit tests from a different location than the /bin/Debug folder.  Sitecore was looking for my FieldTypes.config file in C:\App_Config\FieldTypes.config.  When I commented that line out the test couldn't find the Sitecore license.

**Comment by sergeyshushlyapin** [comment]
Never tried to run it with NUnit since I'm a big xUnit fun ;)

Nevertheless, I guess there might be some NUnit configuration required. For instance, in order to run tests in [NCrunch](http://www.ncrunch.net/) I have to [configure](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Configuration#configuring-ncrunch) the license file copying by myself.

To be researched.

**Comment by sergeyshushlyapin** [comment]
That is interesting. With the default configuration, NUnit3 tests work fine with NCrunch but fail in [TestAdapter](https://visualstudiogallery.msdn.microsoft.com/6ab922d0-21c0-4f06-ab5f-4ecd1fe7175d/view/Discussions/3):
```xml
<setting name="LicenseFile" value="..\..\license.xml" />
<sc.include file="..\..\App_Config\FieldTypes.config" />
```

When I change the settings to the following, the tests work in the adapter but fail in NCrunch:
```xml
<setting name="LicenseFile" value="/license.xml" />
<sc.include file="/App_Config/FieldTypes.config" />
```

**Comment by sergeyshushlyapin** [comment]
@ncipollina, did you get a chance to try the workaround I described above?

I researched the stacktrace and found similar issue in the NUnit backlog:
[NUnit Engine Tests fail if not run from test directory #938](https://github.com/nunit/nunit/issues/938).

```
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   в System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   в System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   в System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   в System.Threading.CompressedStack.runTryCode(Object userData)
   в System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   в System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   в System.Xml.XmlTextReaderImpl.OpenUrl()
   в System.Xml.XmlTextReaderImpl.Read()
   в System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   в System.Xml.XmlDocument.Load(XmlReader reader)
   в System.Xml.XmlDocument.Load(String filename)
   в ClassLibrary1.Class1.HowToCreateSimpleItem() в s:\temp\ClassLibrary1\Class1.cs:строка 30
```

**Comment by ncipollina** [comment]
@sergeyshushlyapin, actually, based on your declaration of being such a big xUnit fan, I switched my tests over to xUnit.

**Comment by sergeyshushlyapin** [comment]
Great ;)
Then I think this issue can be closed.

BTW, if you decided to switch to xUnit, you might be interesting in the [AutoFixture](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/AutoFixture-Samples) extension as well.
