### ISSUE TITLE
Unversioned fields

### ISSUE THREAD

**Issue by kamsar** [sergeyshushlyapin/Sitecore.FakeDb#117]
Is there a way to create _unversioned_ fields using FakeDb? There's a `Shared` property but not a corresponding one for unversioned. It looks like under the covers creating a `DbField` using only a language and value is also implicitly adding it to the latest version instead of creating an unversioned field.

Am I missing something?

**Comment by pveller** [comment]
I don't think you are missing anything. Probably we don't have it yet ;) Thanks for the feature request!

**Comment by kamsar** [comment]
Haha easy to miss. I partially missed it for unicorn - hence the feature
request :)

**Comment by sergeyshushlyapin** [comment]
It was requested some time ago in #47. IMO we shouldn't *tempt* devs to write more code than necessary with the suggested `DbVersion` syntax. I'd start from the minimal fix introducing the `dbfield.Unversioned` property.

Thanks for reporting! I'll take a look on that.

**Comment by sergeyshushlyapin** [comment]
Done in [v0.36.0](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/releases/tag/v0.36.0)
