### ISSUE TITLE
Items created from templates are on the wrong version number

### ISSUE THREAD

**Issue by indyK1ng** [sergeyshushlyapin/Sitecore.FakeDb#122]
I am writing some tests around some code that creates new items based on a template.  While doing this I noticed that the fields for the newly created item would only be populated if we called the code twice.  After some experimentation I found that the version of the item we were getting from the database on the first pass was version 2 but the field data was being put into version 1 on the first run.  I have reproduced this with the code below (using NUnit):

```csharp
        [Test]
        public void FakeDbVersionMisnumber()
        {
            FakeDb = new Db()
            {
                new DbTemplate("ParentTemplate")
                {
                    new DbField("TestField")
                }
            };

            var database = Context.Database;

            TemplateItem parentTemplate = database.Items.GetItem("/sitecore/templates/ParentTemplate");
            Item contentItem = database.Items.GetItem("/sitecore/content");

            contentItem.Editing.BeginEdit();
            var templateBasedItem = ItemManager.CreateItem("TemplateBased", contentItem, parentTemplate.ID);
            contentItem.Editing.EndEdit();

            templateBasedItem.Editing.BeginEdit();
            // Creates the value at version number 1, not version number 2
            templateBasedItem.Fields["TestField"].Value = "TestValue";
            templateBasedItem.Editing.EndEdit();
            
            var newTest = database.GetItem("/sitecore/content/TemplateBased");

            Assert.AreEqual(1, newTest.Version.Number);  // Fails because the newTest item is returning a version number of 2
            // At this point the TestField value returned is an empty string because version 2 hasn't been set
            Assert.AreEqual("TestValue", newTest.Fields["TestField"].Value); // Fails because it is trying to access a value for version 2 which hasn't been set
        }
    }
```

Unfortunately I couldn't reproduce that performing the edit a second time fixed the problem.

I was able to reproduce this issue with 0.31.3 and 0.31.4.

**Comment by sergeyshushlyapin** [comment]
Hi @indyK1ng,

The issue you reported is not reproduced on the latest version, could you please upgrade?

BTW, it's very important to dispose the `db` context properly, so I highly recommend you create and dispose it with `using` statement.

**Comment by indyK1ng** [comment]
Oh jeez, I'm sorry about that.  I forgot that I was looking at the second page of releases and thought 0.31.4 was the latest version.  Thank you for catching that.

Also, thank you for your concern about not disposing of the db context.  When reporting the bug I decided not to show the TearDown method where I am disposing of the object.

Thank you again for your help.
