### ISSUE TITLE
FakeDb.Serialization

### ISSUE THREAD

**Issue by 7bft** [sergeyshushlyapin/Sitecore.FakeDb#130]
Hi, 
would like to use FakeDb.Serialization but hitting a wall. 
Added from nuget, setup some basic test and deserializing an item (including subitems). 
When trying to deserialize an item into /sitecore/system/Settings it seems all items are deserialized into /sitecore/content. 

Am I missing how to do this?
Can you help with this?
Would you rather recommend going the Unicorn way?

Additional suggestion: move the config settings needed to a dedicated include file in app_config/include. 

I used this: 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <pipelines>
      <loadDsDbItem>
        <processor type="Sitecore.FakeDb.Serialization.Pipelines.DeserializeLinkedTemplate, Sitecore.FakeDb.Serialization" />
        <processor type="Sitecore.FakeDb.Serialization.Pipelines.CopySharedFields, Sitecore.FakeDb.Serialization" />
        <processor type="Sitecore.FakeDb.Serialization.Pipelines.CopyVersionedFields, Sitecore.FakeDb.Serialization" />
        <processor type="Sitecore.FakeDb.Serialization.Pipelines.DeserializeDescendants, Sitecore.FakeDb.Serialization" />
      </loadDsDbItem>
      <loadDsDbTemplate>
        <processor type="Sitecore.FakeDb.Serialization.Pipelines.LoadTemplateFields, Sitecore.FakeDb.Serialization" />
      </loadDsDbTemplate>      
    </pipelines>
    <szfolders>
      <folder name="core" value="..\..\..\Data\CoreSerialization\core\" />
      <folder name="master" value="..\..\..\Data\Serialization\master\" />
      <folder name="custom" value="..\..\..\Data\CustomSerialization\master\" />
    </szfolders>
  </sitecore>
</configuration>
```

**Comment by 7bft** [comment]
Well, did some more testing and I can get it to work if I manually set the parent of the deserialized item to the system item. 

<pre>
            using (Sitecore.FakeDb.Db db = new Sitecore.FakeDb.Db())
            {
                var settingsItem = new Sitecore.FakeDb.Serialization.DsDbItem("/sitecore/system/Settings", true);
                settingsItem.ParentID = Sitecore.ItemIDs.SystemRoot;
                db.Add(settingsItem);
                var elementsItem = db.GetItem("/sitecore/system/Settings/Rules/Definitions/Elements");
            }
</pre>
I don't think this is particulary nice and the constructor of DsDbItem should be able to recognize the path correctly.

**Comment by sergeyshushlyapin** [comment]
> I don't think this is particulary nice and the constructor of DsDbItem should be able to recognize the path correctly.

Agree, it's a bug. TBI.

> Additional suggestion: move the config settings needed to a dedicated include file in app_config/include.

Could you please explain the benefits of doing that? The auto include files bring more advanced configuration steps that I'd like to avoid. For instance, I have to remember to copy them to my CI instance. I also have to configure [NCrunch](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Configuration#configuring-ncrunch) to copy them to the working folder.

**Comment by 7bft** [comment]
Regarding app.config include: 
We are building our config's with a homebread system. It requires already quite some effort to keep the config's updated with all the settings released by Sitecore. We have config's for prod/load-test/test/dev/local environment and for delivery & authoring (so overall approx 10+ different variations). 

So being able to patch the settings needed with an include file for the unit tests is much more maintainable than having to merge our settings into the root fakedb config. 

Would categorize as nice to have, but in the long term my assumption would be that it's a lot of work for you too to always have to apply all the fakedb changes you need to updated sitecore config's...

In my opinion having all this settings as include files would be the cleaner way.

**Comment by sergeyshushlyapin** [comment]
Got it. Thanks.

@hermanussen is the author of the [Sitecore.FakeDb.Serialization](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/pull/20) component. Would be nice just to hear his  opinion about moving the serialization settings to the independent config file ;)

**Comment by hermanussen** [comment]
I'm not entirely certain if it's a good idea to move them. I'll look into it after I return from a camping trip that I'm currently on. Rainbow serialization format support will have a higher priority, though.

**Comment by sergeyshushlyapin** [comment]
Fix the main issue part when deserialized items always appeared under the Content item. 
I'm going to close this issue, but if there any other discussion or work to be done, feel free to reopen it.

Available on NuGet as [v1.1.1](https://www.nuget.org/packages/Sitecore.FakeDb/).

**Comment by 7bft** [comment]
Tested it and works fine now! 
Many thx for the fast fix. 
Just in case nobody told you: appreciate your awesome work on FakeDB, keep it up ... ;-)

**Comment by sergeyshushlyapin** [comment]
Glad to dear that, thanks :)

BTW, regarding the following:
> Additional suggestion: move the config settings needed to a dedicated include file in app_config/include.

You may leave the default FakeDb configs *unchanged* and override the **necessary nodes** only in a custom [auto-include](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Configuration#include-files) config file. In this case you won't need to merge the configs every time FaksDb is updated.

> It requires already quite some effort to keep the config's updated with all the settings released by Sitecore.

I might be missing something, but is this really necessary to keep all configs up to date (if we talk about _unit tests_)? Having minimal required configs helps to minimize the maintenance time.
