### ISSUE TITLE
nunitlite-runner.exe not exiting at the end of a test run

### ISSUE THREAD

**Issue by pdragicevich** [sergeyshushlyapin/Sitecore.FakeDb#133]
I have an issue with nunitlite-runner.exe not exiting at the end of a test run, because of a FileWatcher loop in Sitecore.Kernel.dll.  The `shouldStop` boolean is not getting set to false.

Could it be related to   [Using provided NUnit runner in JetBrains TeamCity](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/30) ?  Specifically the license file watcher?

I can run some code after all tests are executed in a `[SetUpFixture]` class `[OneTimeTearDown]` method.  I don't know enough about Sitecore internals.  Is there something I can do to kill this thread?  Or preferably make it stop gracefully?

**Comment by sergeyshushlyapin** [comment]
That's possible. What the Sitecore version you're running?

**Comment by pdragicevich** [comment]
We're on 8.1 update 2.

**Comment by sergeyshushlyapin** [comment]
How can I reproduce it? Preferably in the current FakeDb solution based on xUnit (if possible).

**Comment by sergeyshushlyapin** [comment]
Fixed in [v1.1.2](https://www.nuget.org/packages/Sitecore.FakeDb/).

**Comment by pdragicevich** [comment]
Sorry for not responding with repro steps.  Thanks for the fix, I will give it a try and let you know.
