### ISSUE TITLE
Setting BranchID is not supported

### ISSUE THREAD

**Issue by kamsar** [sergeyshushlyapin/Sitecore.FakeDb#136]
Reproduction:

* Create a fakeDB `Item` instance
* Attempt to update the item's `BranchID` property:

		using (new EditContext(targetItem))
		{
			targetItem.RuntimeSettings.ReadOnlyStatistics = true;
			targetItem.BranchId = ID.Parse(serializedItemData.BranchId);
		}

Result: the BranchID remains the null GUID and is not set.

(and yes, I know `EditContext` is evil. I'ma fix it.)

**Comment by pveller** [comment]
I have some ideas. Off this week but will be happy to look into it when I'm back. You can probably work around it (temporarily) by explicitly defining the BranchId field on your fake template.

**Comment by sergeyshushlyapin** [comment]
@kamsar thanks for reporting the issue.
@pveller the fix seems pretty trivial, you're welcome to take a look on!

**Comment by pveller** [comment]
I will! Give me till Monday please.

**Comment by sergeyshushlyapin** [comment]
@pveller I've merged the fix just before you reported that you'd like to review it. It hasn't been published to the feed, so I'm just waiting ;)

**Comment by pveller** [comment]
No need :) Go ahead and push it up. Thanks!

**Comment by sergeyshushlyapin** [comment]
Yep. I should have mentioned it's a one line fix.
Done in [v1.1.3](https://www.nuget.org/packages/Sitecore.FakeDb/).
