### ISSUE TITLE
ContentItemCustomization should be AutoContentItemCustomization in wiki

### ISSUE THREAD

**Issue by matthile** [sergeyshushlyapin/Sitecore.FakeDb#145]
On https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/AutoFixture-Samples the ContentItemCustomization class name should be AutoContentItemCustomization, no permissions to submit a PR.

### AutoContentItemCustomization
A customization that adds items to the current database. The default database is "master".

```csharp
[Fact]
public void CreateContentItem()
{
  var fixture = new Fixture()
      .Customize(new AutoDbCustomization())
      .Customize(new AutoContentItemCustomization());

  var item = fixture.Create<Item>();
  var database = fixture.Create<Database>();

  var newItem = database.GetItem(item.ID);
  Xunit.Assert.NotNull(newItem);
}
```

**Comment by sergeyshushlyapin** [comment]
Thanks @matthile! Fixed.
