### ISSUE TITLE
Guidance around testing workflow.GetItems(state)

### ISSUE THREAD

**Issue by TimEllison** [sergeyshushlyapin/Sitecore.FakeDb#150]
Howdy.

Can someone offer guidance on how to either augment the current fake data provider or to replace it?

Specifically I need a variant that implements GetItemsInWorkflowState(WorkflowInfo).  I have a custom workflow that inherits from Simple Workflow which of course, was implemented so that I can't pass in an IWorkflowProvider otherwise I'd mock.

Thanks!

**Comment by pveller** [comment]
You can replace it with your own but it's not a simple config patch. Take a look at #146, for example.

**Comment by TimEllison** [comment]
Thanks @pveller.  That was the path I was headed down but did not see how I could replace the provider.  I'll do some more digging to determine that part.

**Comment by pveller** [comment]
@TimEllison, it's a little ugly but you can do it in code: https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/146#issuecomment-251128286

**Comment by sergeyshushlyapin** [comment]
@TimEllison, is there any need to override the data provider? If necessary, you can register a custom provider in the unit test `App.config` file:
```xml
<databases>
  <database id="master">
    <dataProviders hint="list:AddDataProvider">
      <dataProvider ref="dataProviders/custom" />
    </dataProviders>
  </database>
</databases>
<dataProviders>
  <custom type="MyAssembly.CustomDataProvider, MyAssembly" />
</dataProviders>
```

AFAICS, the WorkflowProvider can be mocked without configuration changes. Please take a look on the following sample. Is that what you're looking for?
```csharp
[Fact]
public void GetWorkflowSample()
{
  var stateId = Guid.NewGuid().ToString();
  var workflowProvider = Substitute.For<IWorkflowProvider>();
  var extectedItems = new DataUri[0];

  using (var db = new Db())
  {
    db.Database.WorkflowProvider = workflowProvider;

    var item = db.GetItem("/sitecore/content");
    workflowProvider.GetWorkflow(item).GetItems(stateId)
      .Returns(extectedItems);

    db.Database.WorkflowProvider
      .GetWorkflow(item).GetItems(stateId)
      .Should().BeSameAs(extectedItems);
  }
}
```

**Comment by TimEllison** [comment]
Mocking is preferred.  My impl subclasses the simple workflow impl.  Sadly simple doesn't follow the interface.


Sent from my iPhone.
Tim Ellison

On Nov 21, 2016, at 4:30 PM, sergeyshushlyapin <notifications@github.com<mailto:notifications@github.com>> wrote:


@TimEllison<https://github.com/TimEllison>, is there any need to override the data provider? If necessary, you can register a custom provider in the unit test App.config file:

<databases>
  <database id="master">
    <dataProviders hint="list:AddDataProvider">
      <dataProvider ref="dataProviders/custom" />
    </dataProviders>
  </database>
</databases>
<dataProviders>
  <custom type="MyAssembly.CustomDataProvider, MyAssembly" />
</dataProviders>

AFAICS, the WorkflowProvider can be mocked without configuration changes. Please take a look on the following sample. Is that what you're looking for?

[Fact]
public void GetWorkflowSample()
{
  var stateId = Guid.NewGuid().ToString();
  var workflowProvider = Substitute.For<IWorkflowProvider>();
  var extectedItems = new DataUri[0];

  using (var db = new Db())
  {
    db.Database.WorkflowProvider = workflowProvider;

    var item = db.GetItem("/sitecore/content");
    workflowProvider.GetWorkflow(item).GetItems(stateId)
      .Returns(extectedItems);

    db.Database.WorkflowProvider
      .GetWorkflow(item).GetItems(stateId)
      .Should().BeSameAs(extectedItems);
  }
}

-

**Comment by sergeyshushlyapin** [comment]
> My impl subclasses the simple workflow impl.  Sadly simple doesn't follow the interface.

@TimEllison, could you please bring a code sample to clarify your intentions? What the interface your implementation _doesn't follow_? Is it `IWorkflow` or `IWorkflowProvider`? Either of them can be mocked in a way that allows you use the 'extra' methods that does not exists in the abstraction (sample with [NSubstitute](http://nsubstitute.github.io/)):
```csharp
var workflowProvider = Substitute.For<MyCustomWorkflowProvider, IWorkflowProvider>();
workflowProvider.MyCustomWorkflowProviderMethod();
```

**Comment by TimEllison** [comment]
Sergey.  Thanks for the feedback/responses.  I’m not thinking out of the box to solve this correctly.  I just caught myself trying to mock something I should first isolate.


Tim Ellison
Senior Manager | CapTech
804.405.4874 | tellison@captechconsulting.com<mailto:tellison@captechconsulting.com>

**Comment by sergeyshushlyapin** [comment]
Does it mean the issue can be closed now?

**Comment by TimEllison** [comment]
Yes sir!


Tim Ellison
Senior Manager | CapTech
804.405.4874 | tellison@captechconsulting.com<mailto:tellison@captechconsulting.com>
