### ISSUE TITLE
FakeDb does not generate revision IDs

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#155]
When creating items using FakeDB it does not generate Revision IDs for items with a version.

e.g. string.IsNullOrEmpty(item["__Revision"])  == true.

Note that for items that don't have a version in the target language this field is empty (except if using the field fallback features).

This is my database setup:

         using (Db database = new Db
            {
                new Sitecore.FakeDb.DbItem("Target", new ID(id))
                {
                    new DbItem("Child1")
                    {
                        new DbField("Value")
                        {
                            {"af-ZA", 1, "test"}
                        }
                    },
                    new DbItem("Child2")
                    {
                        new DbField("Value")
                        {
                            {"af-ZA", 1, "test"}
                        }
                    },

                    new DbItem("Child3")
                }
            })

**Comment by sergeyshushlyapin** [comment]
@mikeedwards83 I tried to reproduce the issue on 8.1.3 and 8.2.0. Works on my machine...
Could you please provide a full (minimal) test and specify Sc version?

**Comment by mikeedwards83** [comment]
This test fails:

            Guid id = Guid.NewGuid();

            using (Db database = new Db
            {
                new Sitecore.FakeDb.DbItem("Target", new ID(id))
                {
                    new DbItem("Child1")
                    {
                        new DbField("Value")
                        {
                            {"af-ZA", 1, "test"}
                        }
                    },
                    new DbItem("Child2")
                    {
                        new DbField("Value")
                        {
                            {"af-ZA", 1, "test"}
                        }
                    },

                    new DbItem("Child3")
                }
            })
            {

                var item  = database.GetItem("/sitecore/content/target/child1", "af-ZA");

                Assert.IsFalse(string.IsNullOrEmpty(item["__Revision"]));
             }

**Comment by sergeyshushlyapin** [comment]
Ok, now I can reproduce it, thanks. It's important to _read_ the item in a custom language.

**Comment by sergeyshushlyapin** [comment]
Fixed in [v1.3.4](https://www.nuget.org/packages/Sitecore.FakeDb/).
