### ISSUE TITLE
Will Item Language Fallback work?

### ISSUE THREAD

**Issue by pbering** [sergeyshushlyapin/Sitecore.FakeDb#160]
Hi,

Is it possible? out-of-the-box it seems that item.IsFallback is always false...

**Comment by sergeyshushlyapin** [comment]
The Language Fallback functionality is disabled OOTB in Sitecore as stated in the `Sitecore.LanguageFallback.config`:
```
Purpose: This include file contains all needed functionality for the language fallback feature on field and item levels.
Note that both item and field level fallback functionality is disabled by default for out of the box 'shell' and 'website' sites.
In order to enable this feature, you will need to set the config patches for those sites to 'true'.
```

The config is not included into FakeDb but can be added as [auto-include file](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/26#issuecomment-100333650) on a developer's side if necessary.

> it seems that item.IsFallback is always false

Depending on your goals, it might be enough to set it to `true` _without_ enabling the language fallback functionality. AFAICS, the setting returns `true` if the `OriginalLanguage` property is not null:
```csharp
using (var db = new Db { new DbItem("Home") })
{
    var item = db.GetItem("/sitecore/content/home");
    item.OriginalLanguage = Language.Parse("en");
    Assert.True(item.IsFallback);
}
```

Please let me know if the suggested workaround work out for you.
