### ISSUE TITLE
Certain template inheritance combinations throw "field not found" error

### ISSUE THREAD

**Issue by celston** [sergeyshushlyapin/Sitecore.FakeDb#165]
While trying to recreate a real-world scenario of existing Sitecore templates that inherit fields from each other, I ran into a strange error:

> Item field not found. Item: 'Item Two', '{046655DC-7E41-4BDC-AA78-694524CCADC3}'; field: '{C28F483D-1A31-4EA0-A990-028D76B57F1B}'.

The code I was implementing was rather complex so I wanted to single out the scenario into a single unit test.  See the following class below with 3 test cases.  Two pass and one fails ("EditItems_SharedInheritence_Fail").  In the failing scenario, I have two templates that each have their own unique field.  I have a third template that inherits from template 1 and a fourth that inherits from both template 1 and 2.  My current workaround is to put all of my fields in one template that all other templates inherit from but that's truly recreating my real-world scenario.

`namespace Example
{
    [TestClass]
    public class FakeDbBugTests
    {
        private static ID field1Id = ID.NewID;
        private static ID field2Id = ID.NewID;
        private static ID field3Id = ID.NewID;
        private static DbField field1 = new DbField("Field One", field1Id);
        private static DbField field2 = new DbField("Field Two", field2Id);
        private static DbField field3 = new DbField("Field Three", field3Id);
        private static ID template1Id = ID.NewID;
        private static ID template2Id = ID.NewID;
        private static ID template3Id = ID.NewID;
        private static ID template4Id = ID.NewID;
        private static ID item1Id = ID.NewID;
        private static ID item2Id = ID.NewID;
        private static ID item3Id = ID.NewID;

        [TestMethod]
        public void EditItems_AllFieldsInOneTemplate_Pass()
        {
            using (Db db = new Db())
            {
                db.Add(new DbTemplate("Template One", template1Id)
                {
                    field1,
                    field2,
                    field3
                });
                db.Add(new DbTemplate("Template Two", template2Id)
                {
                    BaseIDs = new []{template1Id}
                });
                db.Add(new DbTemplate("Template Three", template3Id)
                {
                    BaseIDs = new[] {template2Id}
                });

                db.Add(new DbItem("Item One", item1Id, template1Id));
                db.Add(new DbItem("Item Two", item2Id, template2Id));
                db.Add(new DbItem("Item Three", item3Id, template3Id));

                Item item1 = db.GetItem(item1Id);
                item1.Editing.BeginEdit();
                item1[field1Id] = "Value One";
                item1[field2Id] = "Value Two";
                item1[field3Id] = "Value Three";
                item1.Editing.EndEdit();

                Item item2 = db.GetItem(item1Id);
                item2.Editing.BeginEdit();
                item2[field1Id] = "Value One";
                item2[field2Id] = "Value Two";
                item2[field3Id] = "Value Three";
                item2.Editing.EndEdit();

                Item item3 = db.GetItem(item1Id);
                item3.Editing.BeginEdit();
                item3[field1Id] = "Value One";
                item3[field2Id] = "Value Two";
                item3[field3Id] = "Value Three";
                item3.Editing.EndEdit();
            }
        }

        [TestMethod]
        public void EditItems_DoubleInheritance_Pass()
        {
            using (Db db = new Db())
            {
                db.Add(new DbTemplate("Template One", template1Id)
                {
                    field1
                });
                db.Add(new DbTemplate("Template Two", template2Id)
                {
                    BaseIDs = new []{template1Id},
                    Fields =
                    {
                        field2
                    }
                });
                db.Add(new DbTemplate("Template Three", template3Id)
                {
                    BaseIDs = new []{template2Id},
                    Fields =
                    {
                        field3
                    }
                });

                db.Add(new DbItem("Item One", item1Id, template1Id));
                db.Add(new DbItem("Item Two", item2Id, template2Id));
                db.Add(new DbItem("Item Three", item3Id, template3Id));

                Item item1 = db.GetItem(item1Id);
                item1.Editing.BeginEdit();
                item1[field1Id] = "Value One";
                item1.Editing.EndEdit();

                Item item2 = db.GetItem(item2Id);
                item2.Editing.BeginEdit();
                item2[field1Id] = "Value One";
                item2[field2Id] = "Value Two";
                item2.Editing.EndEdit();

                Item item3 = db.GetItem(item3Id);
                item3.Editing.BeginEdit();
                item3[field1Id] = "Value One";
                item3[field2Id] = "Value Two";
                item3[field3Id] = "Value Three";
                item3.Editing.EndEdit();
            }
        }

        [TestMethod]
        public void EditItems_SharedInheritence_Fail()
        {
            using (Db db = new Db())
            {
                db.Add(new DbTemplate("Template One", template1Id)
                {
                    field1
                });
                db.Add(new DbTemplate("Template Two", template2Id)
                {
                    field2
                });
                db.Add(new DbTemplate("Template Three", template3Id)
                {
                    BaseIDs = new[] { template1Id }
                });
                db.Add(new DbTemplate("Template Four", template4Id)
                {
                    BaseIDs = new[] { template1Id, template2Id }
                });

                db.Add(new DbItem("Item One", item1Id, template3Id));
                db.Add(new DbItem("Item Two", item2Id, template4Id));

                Item item1 = db.GetItem(item1Id);
                item1.Editing.BeginEdit();
                item1[field1Id] = "Value One";
                item1.Editing.EndEdit();

                Item item2 = db.GetItem(item2Id);
                item2.Editing.BeginEdit();
                item2["Field One"] = "Value One";
                item2["Field Two"] = "Value Two";

                // next line throws "Item field not found. Item: 'Item Two', '{046655DC-7E41-4BDC-AA78-694524CCADC3}'; field: '{C28F483D-1A31-4EA0-A990-028D76B57F1B}'."
                item2.Editing.EndEdit();
            }
        }
    }
}`

**Comment by sergeyshushlyapin** [comment]
@celston, thanks for reporting this issue!

I can reproduce it in `master`, and it seems the functionality works fine in the [`no-commands`](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commits/no-commands) branch which should simplify some things moving fake logic from Commands to DataProvider.

I'll check what needs to be finished in those branch and get back to this issue.

**Comment by sergeyshushlyapin** [comment]
Fixed in [v1.5.0](https://www.nuget.org/packages/Sitecore.FakeDb/).
