### ISSUE TITLE
Option to manually set the Sitecore AppDomainAppPath

### ISSUE THREAD

**Issue by martinkotula** [sergeyshushlyapin/Sitecore.FakeDb#170]
Hi, 

this relates to the issue #139. As far as I can see the ConfigReader.SetAppDomainAppPath is looking for the bin directory and setts it parent folder to be the Sitecore AppDomainAppPath. That works well when running tests from the source directory structure.

In our case we are outputting our unit tests into a different directory and running those unit tests from there. I would not like to have to recreate the Sitecore config directory structure each time.

So do you think an option to manually set the  Sitecore AppDomainAppPath would be possible? Or is there currently a way to do it?

**Comment by sergeyshushlyapin** [comment]
@martinkotula, I researched it a bit. Setting the `SetAppDomainAppPath` is an enabler for #26 (auto-include files). All the other functionality works fine. 

> I would not like to have to recreate the Sitecore config directory structure each time.

I would even say you *should not*. IMO, the configuration for unit tests should not require auto include files. Is there an option to redesign your configuration to keep it in the tests `App.config` file?

**Comment by martinkotula** [comment]
We are using Sitecore 8.2 and the only reason for adding the auto-include configs was avoiding the 
> Sitecore.Exceptions.ConfigurationException
> Could not create instance of type: Sitecore.Data.Database. No matching constructor was found. 

The solution to this issue was proposed in #139 and it uses the auto-include config. Can the same be achieved with app.config file?

**Comment by sergeyshushlyapin** [comment]
Ah, got it. You can edit the database setting directly in your tests `App.config` file (without using auto-include configs):
```xml
    <!-- DATABASE TYPE
         For Sitecore versions prior to 8.2 should be 'Sitecore.Data.Database, Sitecore.Kernel'.
         For Sitecore 8.2 and later should be 'Sitecore.Data.DefaultDatabase, Sitecore.Kernel'. -->
    <sc.variable name="databaseType" value="Sitecore.Data.DefaultDatabase, Sitecore.Kernel" />
```

**Comment by martinkotula** [comment]
Ah, totally missed that. Thanks!

Think it would be good to make note of this optional step in https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Installation

**Comment by sergeyshushlyapin** [comment]
[Done](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Installation#configuring-the-database-type-for-sitecore-82-and-later). Thanks!
