### ISSUE TITLE
Unable to add item to a parent in 1.6.0

### ISSUE THREAD

**Issue by codingdennis** [sergeyshushlyapin/Sitecore.FakeDb#177]
Hello,

I am not sure if it is just me, however I was trying to write a simple test using version 1.6.0 (1.5.0 might be the same) using the code below:
```csharp
        [Fact]
        public void ItemAddedToParentShouldNotBeNull()
        {
            using (var db = new Db())
            {
                db.Add(new DbItem("home", ID.NewID));
                using (new SecurityDisabler())
                {
                    var home = db.GetItem("/sitecore/content/home");
                    var templateID = new TemplateID(ID.NewID);

                    var child = home.Add("child", templateID);
                    child.Should().NotBeNull();
                }
            }
        }
```
The child object is always null. In version 1.3.5 this was working fine. Any ideas?

Thanks,
Dennis

**Comment by sergeyshushlyapin** [comment]
@codingdennis, thanks for reporting this. I investigated the issue, it's not a bug (even if it was mistakenly working before ;).

When you want to create an item using FakeDb API and the template is not defined, it's generated _automatically_. That allows you to write the following code which creates `Home` item with new auto-generated template:

```
using (var db = new Db
{
    new DbItem("Home") { {"Title","Hello" } }
})
```

Template auto-generation works for `DbItem`s only. If you want to add an item using native Sitecore API, you have to add the template in advance:

```
using (var db = new Db())
{
  // Add child template
  var templateID = new TemplateID(ID.NewID);
  var childTemplate = new DbTemplate("child", templateID);
  db.Add(childTemplate);

  db.Add(new DbItem("home", ID.NewID));
  using (new SecurityDisabler())
  {
    Sitecore.Data.Items.Item home = db.GetItem("/sitecore/content/home");

    var child = home.Add("child", templateID);
    child.Should().NotBeNull();
  }
}
```

**Comment by pveller** [comment]
That's because the database doesn't have the template with templateId. Drop that parameter, let FakeDb generate a template for you, and it should work. Or create a template first and then use it to create a new child item.

**Comment by sergeyshushlyapin** [comment]
@pveller, unfortunately in this line the template parameter cannot be dropped because `home` is a Sitecore `Item`, not a `DbItem` ;)
```
    var child = home.Add("child", templateID);
    child.Should().NotBeNull();
```

It requires a `TemplateID` instance.

**Comment by pveller** [comment]
Right. Still, need a template :) long time no see btw!

**Comment by codingdennis** [comment]
Thanks @sergeyshushlyapin and @pveller. I was thinking that as well and I did try adding a template to the db beforehand but it did not work for some reason. It is all good now :)

**Comment by sergeyshushlyapin** [comment]
Good. Closed.
