### ISSUE TITLE
Wish:Feature or example on how to use paching of LicenseFile setting in *.config

### ISSUE THREAD

**Issue by michaelthyregod** [sergeyshushlyapin/Sitecore.FakeDb#180]
In Sitecore.FakeDb's configuration that is applied there is a setting called "LicenseFile", which tells Sitecore.FakeDb where the licensefile for Sitecore is located. It would be great if the ConfigReader of Sitecore.FakeDb supported a way to patch this setting, making it easier to upgrade Sitecore.FakeDb in a big solution with many test projects that is using Sitecore.FakeDb (Habitat).

If this is already supported, please add something to the wiki where it is shown how to do it, because I have not been able to make it work so far.

**Comment by sergeyshushlyapin** [comment]
Thanks for reporting this, @michaelthyregod.

I'd expect the regular Sitecore patching to work here, but IIRC, there might be some issues with that. Needs to be investigated.

**Comment by michaelthyregod** [comment]
I've figured out how to make it work - so closing this ticket.
