### ISSUE TITLE
Cannot get content profile from item because fast query id format is not fully supported

### ISSUE THREAD

**Issue by ethan-agencyQ** [sergeyshushlyapin/Sitecore.FakeDb#182]
Recently I tried to test my service that CRUD profile cards on items. But my service cannot get the profiles from any item in unit tests. So I decompiled into Sitecore and found out that Sitecore is using a fast query to get the content profile from items. Here is the call trace:

> (entry point, initializing tracking field)
> Sitecore.Analytics.Data.TrackingField.TrackingField(Field innerField)
> Sitecore.Analytics.Data.TrackingField.Initialize()
> Sitecore.Analytics.Data.TrackingField.InitializeProfiles()
> Sitecore.Analytics.Data.ContentProfile.Parse(XElement node, Item item, AnalyticsItems analytics)
> Sitecore.Analytics.Data.Items.Profiles
> Sitecore.Analytics.Data.Items.ItemRecords<ProfileItem>.FindByName(string name)
> (found error, cannot find profile by name)

Basically this is the query Sitecore uses to get profile by name:
`fast://*[@@id = "12bd7e35-437b-449c-b931-23cfa12c03d8"]//*[@@name = "myprofilename"]`

Then I did some fast query experiments in FakeDB:

- fast://*[@@id = "**12bd7e35-437b-449c-b931-23cfa12c03d8**"]//*[@@name = "myprofilename"] - FAILED
- fast://*[@@id = "**{12bd7e35-437b-449c-b931-23cfa12c03d8}**"]//*[@@name = "myprofilename"] - FAILED
- fast://*[@@id = "**12BD7E35-437B-449C-B931-23CFA12C03D8**"]//*[@@name = "myprofilename"] - FAILED
- fast://*[@@id = "**{12BD7E35-437B-449C-B931-23CFA12C03D8}**"]//*[@@name = "myprofilename"] - SUCCESS

So it seems that FakeDb does not support fast search when the id is lowercased and/or without '{}', yet Sitecore uses an id that is lowercased without '{}' in a fast query when it parses profile from tracking field. I wonder if there is a way to work around this situation?

**Comment by sergeyshushlyapin** [comment]
In Sitecore, there is a `SqlDataProvider` which [translates the FastQuery syntax into SQL script](http://www.studert.com/translate-sitecore-fast-queries-to-sql/). FakeDb does not use SQL data provider  to avoid database connection. This also means that all the real fast query logic is unavailable. Actually, it simply behaves as [regular Sitecore query](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb/Data/DataProviders/FakeDataProvider.cs#L378).

Enabling such a limited FQ support probably was a doubtful decision. It allowed to write unit tests for some very simple scenarios, but integration tests were always required to check everything works fine on a real instance.

> I wonder if there is a way to work around this situation?

I'd help if I knew more about you scenario. A sample test is highly appreciated.

I also often recommend to look into [new abstaractions introduced in Sitecore 8.2](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/178#issuecomment-305314753). Some scenarios might be mocked without FakeDb now.

**Comment by ethan-agencyQ** [comment]
Thanks! Here is the function I want to test:
```
public IEnumerable<ProfileCardItem> GetItemProfileCards(Item item)
{
    var trackingField = new TrackingField(item.Fields[AnalyticsIds.TrackingField]);
    var cards = trackingField.Profiles
        .Select(p => p.Presets.Keys.Select(k => p.GetPreset(k)))
        .SelectMany(p => p);
    return cards;
}
```

And here is the test I wrote for it:
```
[Theory]
[AutoDbData]
//HasAnalytics and DBContentProfile are custom code 
//that inject profile items and templates into FakeDB
public void GetItemProfileCards_ShouldGetCards(
    [HasAnalytics]Db db, 
    [Content]DbContentProfile dbProfile,
    [Content]DbItem dbItem)
{
    var profileCard = new ProfileCardItem(db.GetItem(dbProfile.ProfileCardItems[0].ID));
    //TrackingData is a custom object to make assigning value to tracking field easier
    var serializer = new XmlSerializer(typeof(TrackingData));
    using (TextReader reader = new StringReader(profileCard.ProfileCardValue))
    {
        var tracking = (TrackingData)serializer.Deserialize(reader);
        tracking.Profiles.First().Presets = 
        new List<Preset>() { new Preset() { Name = profileCard.Name, Percent = 100 } };
        using(var writer = new StringWriter())
        {
            serializer.Serialize(writer, tracking);
            dbItem.Add(AnalyticsIds.TrackingField, writer.ToString());
        }
    }
    var item = db.GetItem(dbItem.ID);

    var sut = new MyService();
    var cards = sut.GetItemProfileCards(item);

    cards.Should().BeNullOrEmpty("Get item profile cards should never return null");
    cards.Count().Should().Be(1);
    cards.First().Name.Should().Be(profileCard.Name);
}
```

**Comment by sergeyshushlyapin** [comment]
Closing this issue since there is nothing I can do about it. Feel free to reopen if new ideas appear.
