### ISSUE TITLE
SC9: MediaManager no Provider property

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#188]
The MediaManager in SC9 no longer has a Provider property:

Error : Glass.Mapper.Sc.FakeDb.GlassHtmlFixture.RenderLink_LinkWithMixedPropertiesAndParameters
System.MissingMethodException : Method not found: 'Sitecore.Resources.Media.MediaProvider Sitecore.Resources.Media.MediaManager.get_Provider()'.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at Sitecore.FakeDb.Resources.Media.MediaProviderSwitcher..ctor(MediaProvider innerProvider)
   at Glass.Mapper.Sc.FakeDb.GlassHtmlFixture.Setup() in E:\github\Glass.Mapper\Tests\Unit Tests\Glass.Mapper.Sc.FakeDb\GlassHtmlFixture.cs:line 57
--TearDown
   at Glass.Mapper.Sc.FakeDb.GlassHtmlFixture.TearDown() in E:\github\Glass.Mapper\Tests\Unit Tests\Glass.Mapper.Sc.FakeDb\GlassHtmlFixture.cs:line 66

This can be seen in the following build:

http://build.glass.lu/viewLog.html?buildId=3772&buildTypeId=bt25&tab=buildLog&_focus=20262#_state=20262

**Comment by sergeyshushlyapin** [comment]
Unfortunatelly FakeDb cannot help here. I'll restore my [premature commit](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commit/46d12fffee77e1afbdd2be74426d03475cc4ba2f#diff-6aff0a6e891b93ba6678d084a50bfe36) as soon as Sitetecore 9 is publicly available.

The recomendation is to stop using FakeDb `MediaProviderSwitcher` and use new Sitecore abstract class `Sitecore.Abstractions.BaseMediaManager`. You may find some tips how to achieve that [here](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/175) and [here](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/pull/154#issue-194631353).

**Comment by sergeyshushlyapin** [comment]
Marked as obsolete in [v1.7.4](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/releases/tag/v1.7.4). Removed in v2.
