### ISSUE TITLE
Field not reflecting correct values on a multi lingual item

### ISSUE THREAD

**Issue by bhatiarahul10** [sergeyshushlyapin/Sitecore.FakeDb#192]
Hi @pveller

I am trying to create a multi lingual item however I am not following the way its specified in the wiki.
Below is the code that I have written
I create a DB template with fields
var itemTemplate = new DbTemplate("Base Template", tempSitecoreId);
foreach (var f in _fields)
{
itemTemplate.Add(new DbField(f.Key, ID.NewID));
}
Then from this template I create a new DBItem and finally create a version for the item in language.
Then on the item I set the fields
Item item = null; ;
if (!string.IsNullOrEmpty(languages))
{
using (new LanguageSwitcher(languages))
{
var dbItem = new DbItem(_name, ID.NewID, itemTemplate.ID);
dbItem.AddVersion(languages);
_siteCoreDb.Add(dbItem);
item = _siteCoreDb.Database.GetItem(dbItem.ID, Language.Parse(languages ?? "en"));
SetFields(item);
}
}
return item;

Setting Fields
item.Editing.BeginEdit()
item.Fields["FieldName"].Value="Git"

This all works fine until the language is English, however when using some other language say "ja" the values get set in En language item leading to a failing test case which needs the fields to be set upon Japanese item.

Please suggest. Also I need to make the item in this way only as I am passing all the parameters at runtime from the test itself

**Comment by sergeyshushlyapin** [comment]
@bhatiarahul10, could you please publish the minimal working (failing) test and the SUT?

**Comment by bhatiarahul10** [comment]
Here's the link to my git repo . https://github.com/bhatiarahul10/Sitecore
I have pushed in two sample tests

**Comment by sergeyshushlyapin** [comment]
Closing this issue. If still actual, please provide [MCVE](https://stackoverflow.com/help/mcve) and reopen.
