### ISSUE TITLE
Support for Template Sections

### ISSUE THREAD

**Issue by rmatherly** [sergeyshushlyapin/Sitecore.FakeDb#196]
I can't seem to figure out a way to create a template with sections, and I'm not sure if it is supported.  I am trying to test some code that loops through all the fields on an item and builds a dictionary from all the fields in a particular section using the Section property of the field.

It would be nice to be able to do something like this:
```
new DbTemplate("TemplateName")
{
    new DbSection("Section1")
    {
        new DbField("Field1"),
        new DbField("Field2")
    },
    new DbSection("Section2")
    {
        new DbField("Field3"),
        new DbField("Field4")
    }
}
```

**Comment by sergeyshushlyapin** [comment]
@rmatherly thanks for the request. AFAICT, the customizable sections are not supported. Historically, the `Data` section created automatically satisfied the testing needs, but I agree that your scenario requires more advanced section configuration.
I cannot promise you fast implementation, but I'm always open for a PR ;)

**Comment by rmatherly** [comment]
@sergeyshushlyapin thanks for the quick response and for creating such a helpful testing tool.  After putting some thought into it, I'm going to change the code to pull the individual fields.  I feel that the Sections in Sitecore are really meant as a means of visual organization for the Content Editors and probably should not be used as groupings in the code.  I'm closing this for now.
