### ISSUE TITLE
Does FakeDb distinguish between item's Name and DisplayName?

### ISSUE THREAD

**Issue by cheemingli** [sergeyshushlyapin/Sitecore.FakeDb#197]
I have a test where the item's Name is different from the DisplayName but I can't seem to fill the item's DisplayName.

Is it possible?

**Comment by pveller** [comment]
`item.DisplayName` is a regular `__Display name` field. Just go ahead and set it on your test item

**Comment by cheemingli** [comment]
It doesn't seem to work.

I've tried using the field ID `FieldIDs.DisplayName` and the field name `__Display name`.

A sample piece of code I've extracted from some builder class (that's why the DbFieldCollection is used to add fields to the fake item).
```
var dbItem = new DbItem("NameOfItem", ID.NewID);

DbFieldCollection fields = new DbFieldCollection();
fields.Add("__Display name", "Name of item");
foreach (DbField field in fields)
{
    dbItem.Fields.Add(field);
}

fakeDb.Add(dbItem)
```

**Comment by pveller** [comment]
Take a look at this test example: https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/1e76bd656f405f5e0f781c06832dfbdd9247beec/test/Sitecore.FakeDb.Tests/Data/Items/ItemAppearanceTest.cs

**Comment by cheemingli** [comment]
I'm missing tests where the item's name is different from the display name. 
It looks like it is not possible to have a fake item where the name and display name are different.

**Comment by pveller** [comment]
From that test case that I shared with you:

```
    [Fact]
    public void ShouldSetDisplayNameInDifferencCultures()
    {
      // arrange
      using (var db = new Db
                        {
                          new DbItem("home") { { FieldIDs.DisplayName, "Home!" } }
                        })
      {
        db.GetItem("/sitecore/content/home", "en")[FieldIDs.DisplayName].Should().Be("Home!");
        db.GetItem("/sitecore/content/home", "uk-UA")[FieldIDs.DisplayName].Should().BeEmpty();
      }
    }
```

**Comment by cheemingli** [comment]
Hmm. Ok I will try it out and let you know the outcome. Will try your simple example first and then try to get it working in my solution.

**Comment by cheemingli** [comment]
Tested with the test case you've shared and with my own  example I've posted. Both passes.
I will compare with the test case in my test solution and try to figure out what is different.
Thanks for the help!
