### ISSUE TITLE
Update Sitecore.FakeDb.AutoFixture Nuget reference to AutoFixture

### ISSUE THREAD

**Issue by tkooser** [sergeyshushlyapin/Sitecore.FakeDb#198]
The Sitecore.FakeDb.AutoFixture Nuget package references AutoFixture versions between 3.0 and 4.0. Current AutoFixture version is 4.2.0.

**Comment by sergeyshushlyapin** [comment]
Implemented by @Tchami in #199 and released as [v2.0.0-alpha1](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/releases/tag/v2.0.0-alpha1).
