### ISSUE TITLE
Include configs

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#26]
Does FakeDb make use of Sitecore Include config files? I want to separate out my config changes for my testing from the main App.config.

**Comment by sergeyshushlyapin** [comment]
Implemented basic functionality. Config files to include should be located in the `<tests>\App_Config\Include` folder (e.g. [AutoIncludeSample.config](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb.Tests/App_Config/Include/Sitecore.FakeDb.AutoIncludeSample.config)).

Please let me know if you think it may sense to introduce some kind of setting to allow including configs outside of the project root. My biggest concern is potential misuse of the feature pointing it to a real `App_Config\Include` folder with numerous config files.

**Comment by sergeyshushlyapin** [comment]
Added wiki page:
https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Configuration
