### ISSUE TITLE
Automatic template generation needs to be a little smarter

### ISSUE THREAD

**Issue by pveller** [sergeyshushlyapin/Sitecore.FakeDb#34]
FakeDb will generate a template for a `DbItem` that was not given a specific template. FakeDb also reuses the template from the sibling item added previously in case item definitions match (i.e. same fields). I believe FakeDb **shouldn't reuse templates unless those were auto-generated**. Here's an example:

```csharp
using (var db = new Db
{
    new DbTemplate("Site Root", new ID(myID),
    new DbItem("site", ID.NewID, new ID(myID))
    {
        new DbItem("home")
    },
    new DbItem("outside")
})
{
    var home = db.GetItem("/sitecore/content/site/home");
    var outside = db.GetItem("/sitecore/content/outside");

    outside.TemplateID.Should().NotBe(myID) // <-- Fails
}
```

`outside` item will be created with `myID` as its `TemplateID`. I think it should have been given its own template. 

@sergeyshushlyapin , let me know what you think. I will send a pull request shortly :)

**Comment by sergeyshushlyapin** [comment]
Sounds reasonable. Waiting for request :)
Thanks!
