### ISSUE TITLE
Fix Template.OwnFields

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#44]
Now all the standard fields are treated as 'own' template fields. The following test returns `12` *own* fields instead of the expected one:

```csharp
[Fact]
public void ShouldGetOwnFields()
{
  // arrange
  var templateId = ID.NewID;

  using (var db = new Db
                    {
                      new DbTemplate(templateId) { "expected own field" },
                      new DbItem("home", ID.NewID, templateId)
                    })
  {
    var item = db.GetItem("/sitecore/content/home");

    // assert
    item.Template.OwnFields.Count()
      .Should().Be(1, string.Join("\n\r", item.Template.OwnFields.Select(f => f.Name)));
    item.Template.OwnFields.Single().Name.Should().Be("expected own field");
  }
}
```

**Comment by pveller** [comment]
I have implemented field inheritance from the base templates a while ago. I wanted to then go ahead and create a `standard template` that would have standard fields. We then only need to give every `DbTemplate` (generated templates included) a base template unless one was already given at creation. This will probably solve the `own` fields issue. Should I implement it? :) I know I owe you something else on the templates anyway.

**Comment by sergeyshushlyapin** [comment]
Thanks Pavel! I think I close to finish it. Just need to fix couple of failing tests.
