### ISSUE TITLE
Wish: Add support of versioned/unversioned fields with a type

### ISSUE THREAD

**Issue by AlenPelin** [sergeyshushlyapin/Sitecore.FakeDb#47]
In current implementation it is not possible to versioned/unversioned field with a type. The only available syntax for adding versioned field is:

```c#
new DbField("Title")
{
  { "en", 1, "Hello!" },
  { "en", 2, "Welcome!" }
}
```

I suggest to add DbVersion:
```c#
new DbItem("MyItem")
{
  new DbVersion("en") // for unversioned fields
  {
    new DbField("UnversionedLink") { Value = someId.ToString(), Type = "droptree", Shared = false },
  },
  new DbVersion("en", 4) // for versioned fields
  {
    new DbField("VersionedLink") { Value = someId.ToString(), Type = "droptree", Shared = false },
  }
}
```
and/or extend original syntax:
```c#
new DbField("VersionedLink")
{
  { "en", 4, someId.ToString(), "droptree" },
},
new DbField("UnversionedLink")
{
  { "en", someId.ToString(), "droptree" },
}
```

**Comment by pveller** [comment]
I like the `DbVersion`. Good idea! The "extended" syntax is limiting in a way. We will probably still need to support the existing syntax not to break all the tests already written with it. I know we have quite a few.

**Comment by sergeyshushlyapin** [comment]
The `DbVersion` type looks reasonable here. The only concern that stops me from implementing it is the numerous examples of misusing the framework.

For some reason devs often try to *recreate* the full content tree in code using real paths, names and ids. That is time consuming and leads to the huge and expensive (in maintenance) test setup methods which I'm trying to avoid by any means (creating only [minimal](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Creating-a-Simple-Item) and relevant test content; using [AutoFixture](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/AutoFixture-Samples#create-an-item-based-on-a-custom-template)).

I definitely cannot prevent devs from writing redundant code. I'm just have doubts if the suggested API will bring more benefits that drawbacks. Any thoughts?

**Comment by pveller** [comment]
What if we changed/repurposed `DbField.Add/2` to add a value to a language version of an `Unversioned` field? It would be a breaking change, true, but the current ` var version = this.GetLatestVersion(language) + 1;` behavior is also not exactly intuitive. And if the `DbField.Add/3` changed the  order of the last two arguments (value first and version last), we would easily default the version to `Version.Latest`. Just thinking of the alternatives. May also help to add an explicit boolean `Unversioned` similar to already supported `Shared`. In Sitecore API a field has these too booleans in a form of `IsShared` and `IsUnversioned`. And maybe the behavior of `DbField.Add/2` can change based on whether the field is `Unversioned`? This way it's no longer a breaking change! Anyway, just thinking out loud.

**Comment by sergeyshushlyapin** [comment]
I played around a bit with this and end up with the following solution:
```csharp
using (var db = new Db
  {
    new DbItem("home")
      {
        new UnversionedDbField("Field")
          {
            { "en", 1, "en value initial" },
            { "en", 2, "en value expected" },
            { "da", 1, "da value initial" },
            { "da", 2, "da value expected" }
          }
      }
  })
{
  db.GetItem("/sitecore/content/home", "en", 1)["Field"].Should().Be("en value expected");
  db.GetItem("/sitecore/content/home", "en", 2)["Field"].Should().Be("en value expected");
  db.GetItem("/sitecore/content/home", "da", 1)["Field"].Should().Be("da value expected");
  db.GetItem("/sitecore/content/home", "da", 2)["Field"].Should().Be("da value expected");
}
```

The new `UnversionedDbField` class allows to separate the behavior of the different kinds of fields. Now `DbField` handles the *versioned* and *shared* field scenarios. Adding the *unversioned* field logic would make it way to complex. BTW, the new class does not prevent using the collection initializers (unlike Shared/Unversioned property).

**Comment by sergeyshushlyapin** [comment]
Done in [v0.36.0](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/releases/tag/v0.36.0)
