### ISSUE TITLE
Deserialization of base templates broken in latest version

### ISSUE THREAD

**Issue by hermanussen** [sergeyshushlyapin/Sitecore.FakeDb#48]
In version 0.25.1, the following file gives an error when deserializing template items with multiple base templates. Obviously because it attempts to parse a single ID, where it can actually be a list. The file:
https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/2c7afe3dfb032b4740d765696c9659d99a385d52/src/Sitecore.FakeDb.Serialization/Pipelines/CopySharedFields.cs

Perhaps due to a refactoring? I reverted to 0.25.0 and it works correctly there.

(actually, some other stuff appears to be broken after 0.24.0; I'll look into it personally when I have the time)

**Comment by sergeyshushlyapin** [comment]
Thanks for reporting! I'll take a look on this.

**Comment by sergeyshushlyapin** [comment]
Fixed in v0.25.2
