### ISSUE TITLE
Adding a duplicated item throws an exception with a helpless message

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#54]
Message should contain item `id` and `path`.

**Comment by JackTheHack** [comment]
@sergeyshushlyapin Thank you

I also found other places which fail with exception during the import from serialization.

I've seen some tests added in branch issue-55, which I failing in my PC. Are they done for the upcoming serialization duplicate logic?

**Comment by sergeyshushlyapin** [comment]
Yes, I plan to take a look on it this everning.



—
