### ISSUE TITLE
Separate ShouldSupportAutoIncludeFiles test run fails

### ISSUE THREAD

**Issue by JackTheHack** [sergeyshushlyapin/Sitecore.FakeDb#57]
Tried to run ShouldSupportAutoIncludeFiles separatly and it fails.
If I'll add using new Db(){} in the beginning of the test then it works.

```C#
using (var db = new Db()){            }
using (var db = new Db())
{
                var value2 = Sitecore.Configuration.Settings.GetSetting("UnitTestKey");
                Assert.AreEqual(value2, "UnitTestValue");
}
```

**Comment by sergeyshushlyapin** [comment]
Yep! That is the scenario I discovered yesterday as well! Has been fixed and merged into master. 



—

**Comment by sergeyshushlyapin** [comment]
Has been solved by the commit https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commit/a39790463c6e21e36c1e83d8ccfd300209d77c35. Thanks!
