### ISSUE TITLE
Cannot set and get the `__Final Renderings` field value

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#64]
The field `__Final Renderings` is not registered in the Standard template. The test below fails:

```c#
[Theory]
[InlineAutoData("__Final Renderings")]
public void ShouldReadStandardFieldValues(string fieldName, string fieldValue, Db db)
{
  // arrange
  db.Add(new DbItem("home") { { fieldName, fieldValue } });

  // act & assert
  db.GetItem("/sitecore/content/home")[fieldName].Should().Be(fieldValue);
}
```

**Comment by pveller** [comment]
Yep. Have been thinking about the same thing recently :)

**Comment by sergeyshushlyapin** [comment]
Got a request from a teammate :). Adding all the standard fields "I know". Wow! It's 70 lines of `[InlineData]`...

**Comment by sergeyshushlyapin** [comment]
Wondering if all of them needs to be registered in the Standard template... Wouldn't it be better to keep very few standard fields as it is right now and add more in a test if necessary?

**Comment by pveller** [comment]
That's what I have been doing in my tests but I always felt those fields should be on every item because, well, in Sitecore they are, right?

**Comment by sergeyshushlyapin** [comment]
Released as 0.27.1. A follow-up story created.

**Comment by sergeyshushlyapin** [comment]
Unable to run against Sitecore 7.2. Reopen.

**Comment by sergeyshushlyapin** [comment]
Fixed.
