### ISSUE TITLE
Add all the Sitecore Standard fields to the FakeDb Standard Template

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#65]
In the issue #64, the missing `__Final Renderings` field has been added to the Standard Template. All the other existing Sitecore standard fields needs to be registered as well.

It might be challenging to keep the fields set actual for numerous Sitecore versions. Consider implementing some kind of convention like *"read all fields from the `FieldIds` class"*.

**Comment by sergeyshushlyapin** [comment]
Don't want to add the fields manually because of the potential versioning issues mentioned above. In the same time reading the fields using reflection does not allow to set proper names and *Shared* fields. Any suggestions how it could be done?

**Comment by pveller** [comment]
Maybe use the now supported serialization and carry a serialized standard template with all its sections from the most recent Sitecore release? No hardcode, no reflection, and we get both IDs and Names.

**Comment by sergeyshushlyapin** [comment]
Working on this in the `field-factory` branch. My current idea is just to create **all** the fields manually including *ID*, *Name* and  *Shared* fields. Wouldn't like to mix it with the serialization add-in... It definitely should be possible as an optional solution, but should not be a requirement.

Regarding the cross-versioning, I'd keep in FakeDb the "widest" set of fields. I guess that should be the fields from the latest available Sitecore version. That is not ideal, but are there any possible negative consequences of having some extra fields in some cases? E.g. fields from 8.1 on the 7.2-based project..

**Comment by sergeyshushlyapin** [comment]
Using serializations may shift the "fields accuracy" maintaining to the FakeDb users (unless we deliver the serializations as part of the nuget package)..

But, it definitely worth to check, if the fields from serializations will work as expected and won't conflict with the existing *default* standard fields.

**Comment by pveller** [comment]
>> negative consequences of having some extra fields in some cases

Don't think so. Just can't compile against `FieldIDs.FinalLayout` for example, that's why we have our own version of those fields IDs.

**Comment by pveller** [comment]
And I agree re: extra dependency. Didn't realize it was a separate NuGet. You are right. Wouldn't want to have that as a requirement in the base framework.

**Comment by sergeyshushlyapin** [comment]
@pveller: Introduced *Field Builder* (https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commit/211efb101d8a17530a1259b9533c663088d91502) and registered all the *Standard Fields* from 8.1.0 (https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commit/9f855172ffeda96d05120d3d1a5207b4f27a5e9c). Feedback is welcome ;)

**Comment by pveller** [comment]
I like it! With the `FieldInfo` you may as well look at #47 maybe?

**Comment by sergeyshushlyapin** [comment]
Introduced a list of specialized DbField builder's (standard/random fields, from name or id), so there is no the almighty DbField constructor covering all the scenarios any more (c2d6ce9).

**Comment by sergeyshushlyapin** [comment]
Implemented in [v0.35.0](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/releases/tag/v0.35.0).
