### ISSUE TITLE
What is the purpose of disposing Db object?

### ISSUE THREAD

**Issue by AlenPelin** [sergeyshushlyapin/Sitecore.FakeDb#70]
The Db class implements IDisposable interface and in examples this object is always gets disposed via using statement. 

Question: Is there any negative consequences in leaving Db object indisposed?

The reason of this question is shorting the syntax and improving code style from
```c#
using(var db = new Db {
  new DbItem("test") { 
    new DbField("field") { Value = "value" } } })
{
  var test = db.GetItem("/sitecore/content/test");
  Assert.IsNotNull(test);
}
```
to
```c#
var db = new Db {
  new DbItem("test") { 
      new DbField("field") { Value = "value" } } };

var test = db.GetItem("/sitecore/content/test");
Assert.IsNotNull(test);
```

**Comment by pveller** [comment]
Cleaning up all Thread Local state (in Sitecore APIs and FakeDb as well) and making sure each test runs in a clean environment. Otherwise you will see tests polluting one another with templates, items, and other things. Absolutely a must with NCrunch and XUnit 2 parallel tests

**Comment by sergeyshushlyapin** [comment]
Yep, that's true. If you want to shorten your code, consider Autofixture. Sample: https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/61



—

**Comment by AlenPelin** [comment]
Thanks, issue is closed.
