### ISSUE TITLE
Cannot read items from 'outer' db if 'inner' db is disposed

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#78]
I would not recommend to use nested `Db` instances. Nevertheless, the code below should not fail:
```csharp
// arrange
using (var db = new Db { new DbItem("home") })
{
  // act
  using (new Db())
  {
  }

  // assert
  db.GetItem("/sitecore/content/home").Should().NotBeNull(); // fails
}
```

**Comment by pveller** [comment]
Is it even even legal to nest fake databases? :) why would someone want to do so? What's the use case for database nesting? A code that switches between web, master, reporting, session? Any new databases coming our way in 8.x? :)

**Comment by sergeyshushlyapin** [comment]
So, I fully agree with you; this is definitely a wrong way of designing tests. That is not the case if one follows the *arrange-act-assert* pattern and configures `Db` instance in a test. But in case of numerous "helpers", "utils" and other similar stuff the situation is not so obvious...

Since FakeDb is not able to detect 'nested' databases, I guess it should just behave correctly and return items from the *current* db context. I have a feeling that some kind of a `SwitchableDataProvider` should solve this pretty easily.

**Comment by sergeyshushlyapin** [comment]
Done
