### ISSUE TITLE
Wish: Extend FakeDb to use DbBaseTemplate

### ISSUE THREAD

**Issue by vladcheg** [sergeyshushlyapin/Sitecore.FakeDb#88]
Here is an example:
 - Template Folder
    - Template A
    - Template B
```csharp
      var id = ID.NewID;
      var fdb = new Db()
      {
        new DbTemplate("Template Folder")
        {
          new DbTemplate("Template A", id),
          new DbTemplate("Template B"){BaseIDs = new ID[]{id}}
        }
      };
```
I wish you would extend it. Where A is base template for B:
 - Template Folder
    - Template A
    - Template B
```csharp
      var fdb = new Db()
      {
        new DbTemplate("Template Folder")
        {
          new DbTemplate("Template B")
          {
            new DbBaseTemplate("Template A", id)
          }
        }
      };
``` 
Where A and B are base templates for C:
 - Template Folder
    - Template A
    - Template B
    - Template C
```csharp
      var fdb = new Db()
      {
        new DbTemplate("Template Folder")
        {
          new DbTemplate("Template C")
          {
            new DbBaseTemplate("Template A"),
            new DbBaseTemplate("Template B")
          }
        }
      };
``` 
Where A is base template for B and B is base template for C.
 - Template Folder
    - Template A
    - Template B
    - Template C
```csharp
      var fdb = new Db()
      {
        new DbTemplate("Template Folder")
        {
          new DbTemplate("Template C")
          {
            new DbBaseTemplate("Template B")
            {
              new DbBaseTemplate("Template A")
            },
          }
        }
      };
```

**Comment by pveller** [comment]
I see where you're going with this but it makes these templates look *nested*, almost like sub-items or sub-templates. I understand that the `BaseIDs` as a property requires you to define your template IDs in advance and thus the code is not as nice and a fluid, but I don't think nesting is the answer, to be honest. Besides, how would you deal with inheriting from `Template A` more than once? We would probably build smarts to see that the template has been defined before but now it's probably even more confusing - duplication in code that is not reflected in the processing logic. See what I mean?

**Comment by vladcheg** [comment]
Got it. 
Indeed,  if 
```csharp
new DbTemplate("Template A")
{
  new DbTemplate ("Template B")
};
```
in this case B is under A
And if 
```csharp
new DbTemplate("Template A")
{
  new DbBaseTemplate ("Template B")
};
```
in this case they are children.
Yep, you have a point here.

**Comment by sergeyshushlyapin** [comment]
Agree with @pveller that it's confusing. Closed.
