### ISSUE TITLE
Database.GetItem() should return latest version

### ISSUE THREAD

**Issue by mnak** [sergeyshushlyapin/Sitecore.FakeDb#90]
[Fact]
    public void GetItemShouldReturnLatestVersion()
    {
      ID itemId = ID.NewID;
      using (var db = new Db())
      {
        var fieldId = ID.NewID;
        var dbItem = new DbItem("Fake Topic", itemId) {new DbField(fieldId) {{"en", 1, "123"}, {"en", 2, "456"}}};
        db.Add(dbItem);
        //Act
        var topic = Context.Database.GetItem(itemId);
        // Assert
        topic.Versions.Count.Should().Be(2);
        topic.Version.Number.Should().Be(2);
      }
    }

**Comment by sergeyshushlyapin** [comment]
Solved in 7cc043e540039c549db06c83b590f2576dda9a85.
