### ISSUE TITLE
item.Versions[Version.Latest] should return latest version

### ISSUE THREAD

**Issue by mnak** [sergeyshushlyapin/Sitecore.FakeDb#91]
[Fact]
    public void GetLatestVersionShouldReturnLatestVersion()
    {
      ID itemId = ID.NewID;
      using (var db = new Db())
      {
        var fieldId = ID.NewID;
        var dbItem = new DbItem("Fake Topic", itemId) { new DbField(fieldId) { { "en", 1, "123" }, { "en", 2, "456" } } };
        db.Add(dbItem);
        var topic = Context.Database.GetItem(itemId);
        
        // Act
        topic = topic.Versions[Version.Latest];
        
        //Assert
        topic.Versions.Count.Should().Be(2);
        topic.Version.Number.Should().Be(2);
      }
    }

**Comment by sergeyshushlyapin** [comment]
Released as [v0.31.1](https://www.nuget.org/packages/Sitecore.FakeDb/).
