### ISSUE TITLE
FluentAssertions: item.Should().BeNull() hangs up test runner if the item is not null

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#93]
There is an instance of the `DbItem` class which is **not null**. The xunit's `Assert.Null(item)` fails as expected, but the FluentAssertions' code fails with time out:

```csharp
using (var db = new Db { new DbItem("home") })
{
  var item = db.GetItem("/sitecore/content/home");
  //Assert.Null(item);      // works just fine.
  item.Should().BeNull(); // failure is expected, but it hangs the runner up.
}
```

**Comment by pveller** [comment]
I had experienced timeouts after upgrading to FluentAssertion 4 with `collection.Should().Contain(lambda)`. Solved by converting to inspecting a count instead. Our items are `IEnumerable` so it may (just wildly guessing) have something to do with enumerables and v4 of FluentAssertions.

**Comment by pveller** [comment]
Can this be the reason? Timing out trying to construct the error message because of traversing properties?

https://github.com/dennisdoomen/fluentassertions/issues/308

**Comment by pveller** [comment]
I figured it's our `ItemWrapper` that's missing the `ToString()` and it helps the `item.Should().xxx()` validations but I also register a catch-all formatter to override the default one that would build the object graph. @sergeyshushlyapin, see if you like this one. A commit is on the way. btw, I will probably blog about this as teams using FakeDb and FluentAssertions will probably want to do something similar in their test projects.

**Comment by pveller** [comment]
yep, can't do *catch all* formatter. Here's how FluentAssertions finds a formatter:

https://github.com/dennisdoomen/fluentassertions/blob/develop/Src/Core/Formatting/AttributeBasedFormatter.cs#L61

so basically the argument type has to match exactly. I guess the only thing I can do is to add the `ToString()` to the `ItemWrapper` and it will close this issue *per se*. Something is better than nothing, right?
